//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyExams.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Booking_ID { get; set; }
        public int Student_ID { get; set; }
        public int Instructor_ID { get; set; }
        public int Slot_ID { get; set; }
        public System.DateTime Date_Time { get; set; }
        public int Plane_Type_ID { get; set; }
    }
}
