//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyExams.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Session
    {
        public int ID { get; set; }
        public Nullable<int> Map_Number { get; set; }
        public System.DateTime Start_Day { get; set; }
        public System.DateTime End_Day { get; set; }
    
        public virtual Map Map { get; set; }
    }
}
