//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyExams.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor_Slots
    {
        public int Instructor_ID { get; set; }
        public int Slot_ID { get; set; }
        public Nullable<System.DateTime> Date_Time { get; set; }
        public Nullable<bool> Booked { get; set; }
    }
}
