//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyExams.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        public string INVOICE_NUM { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
        public string CUST_ID { get; set; }
    }
}
