//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyExams.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        public string ITEM_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> ON_HAND { get; set; }
        public string CATEGORY { get; set; }
        public string LOCATION { get; set; }
        public Nullable<decimal> PRICE { get; set; }
    }
}
