//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyExams.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkyExamsEntities : DbContext
    {
        public SkyExamsEntities()
            : base("name=SkyExamsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Booking_Status> Booking_Status { get; set; }
        public virtual DbSet<Cessna_172> Cessna_172 { get; set; }
        public virtual DbSet<Cessna_172_RG> Cessna_172_RG { get; set; }
        public virtual DbSet<Cherokee_140> Cherokee_140 { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Employment_Status> Employment_Status { get; set; }
        public virtual DbSet<EventLocation> EventLocations { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<Instructor_Licence> Instructor_Licence { get; set; }
        public virtual DbSet<Instructor_Slots> Instructor_Slots { get; set; }
        public virtual DbSet<Lesson_Plan> Lesson_Plan { get; set; }
        public virtual DbSet<Licence_Type> Licence_Type { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<Plane> Planes { get; set; }
        public virtual DbSet<Plane_Type> Plane_Type { get; set; }
        public virtual DbSet<Question_Type> Question_Type { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<SkyExam> SkyExams { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Student_Instructor> Student_Instructor { get; set; }
        public virtual DbSet<Student_Lesson_Plan> Student_Lesson_Plan { get; set; }
        public virtual DbSet<Student_Licence_Type> Student_Licence_Type { get; set; }
        public virtual DbSet<Student_Resource> Student_Resource { get; set; }
        public virtual DbSet<Study_Resource> Study_Resource { get; set; }
        public virtual DbSet<Sys_User> Sys_User { get; set; }
        public virtual DbSet<Theme_Covered> Theme_Covered { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<Topic_Covered> Topic_Covered { get; set; }
        public virtual DbSet<Twin_Commanche> Twin_Commanche { get; set; }
        public virtual DbSet<uEvent> uEvents { get; set; }
        public virtual DbSet<User_Event> User_Event { get; set; }
        public virtual DbSet<User_Role> User_Role { get; set; }
        public virtual DbSet<UserPassword> UserPasswords { get; set; }
        public virtual DbSet<Verification_Code> Verification_Code { get; set; }
        public virtual DbSet<Zip_Code> Zip_Code { get; set; }
        public virtual DbSet<Profile_Image> Profile_Image { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
    }
}
