//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyExams.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plane_Service
    {
        public int Plane_Service_ID { get; set; }
        public int Plane_ID { get; set; }
        public System.DateTime Last_Service_Date { get; set; }
        public string Reason_For_Service { get; set; }
        public string Parts_Used { get; set; }
    }
}
