//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyExams.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plane_Service
    {
        public int Plane_ID { get; set; }
        public Nullable<System.DateTime> Last_Service_Date { get; set; }
        public string Service_Details { get; set; }
    }
}
