//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyExams.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plane
    {
        public int Plane_ID { get; set; }
        public int Plane_Type_ID { get; set; }
        public string Call_Sign { get; set; }
        public Nullable<int> Hours_Flown { get; set; }
        public Nullable<int> Hours_Until_Service { get; set; }
        public Nullable<bool> In_Service { get; set; }
    }
}
