//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyExams.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plane_Type
    {
        public int Plane_Type_ID { get; set; }
        public string Type_Description { get; set; }
        public byte[] Plane_Image { get; set; }
    }
}
