//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyExams.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPERTY
    {
        public short PROPERTY_ID { get; set; }
        public byte OFFICE_NUM { get; set; }
        public string ADDRESS { get; set; }
        public short SQR_FT { get; set; }
        public byte BDRMS { get; set; }
        public byte FLOORS { get; set; }
        public Nullable<short> MONTHLY_RENT { get; set; }
        public string OWNER_NUM { get; set; }
    }
}
