//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyExams.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration_Sheet
    {
        public int Registration_ID { get; set; }
        public int Sys_User_ID { get; set; }
        public string First_Name { get; set; }
        public string Surname { get; set; }
        public int Plane_Type_ID { get; set; }
        public string Type_Desctription { get; set; }
        public bool Paid { get; set; }
    }
}
