//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyExams.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Lesson_Plan
    {
        public int Student_ID { get; set; }
        public int Lesson_Plan_ID { get; set; }
    }
}
