//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyExams.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Twin_Commanche
    {
        public int Twin_Commanche_ID { get; set; }
        public int Plane_ID { get; set; }
        public string Plane_Description { get; set; }
    }
}
