//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyExams.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uEvent
    {
        public int Event_ID { get; set; }
        public Nullable<System.DateTime> Date_Time { get; set; }
        public int Location_ID { get; set; }
        public Nullable<int> Event_Type_ID { get; set; }
    }
}
