//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyExams.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPassword
    {
        public int Password_ID { get; set; }
        public string Encrypted_password { get; set; }
        public Nullable<System.DateTime> Date_Set { get; set; }
    }
}
