//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyExams
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE_LINE
    {
        public string INVOICE_NUM { get; set; }
        public string ITEM_ID { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<decimal> QUOTED_PRICE { get; set; }
    }
}
