//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyExams
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESIDENT
    {
        public short RESIDENT_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string SURNAME { get; set; }
        public short PROPERTY_ID { get; set; }
    }
}
