//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyExams
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE_REQUEST
    {
        public short SERVICE_ID { get; set; }
        public short PROPERTY_ID { get; set; }
        public byte CATEGORY_NUMBER { get; set; }
        public byte OFFICE_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string STATUS { get; set; }
        public byte EST_HOURS { get; set; }
        public byte SPENT_HOURS { get; set; }
        public Nullable<System.DateTime> NEXT_SERVICE_DATE { get; set; }
    }
}
